# Generated by Django 5.1.1 on 2024-09-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
